version: '3.8'

services:
  sky-agent:
    build:
      context: .
      dockerfile: Dockerfile.sky-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    depends_on:
      - atlassian
      - mcp-proxy

  atlassian:
    build:
      context: .
      dockerfile: ./mcp-servers/Dockerfile.atlassian
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    restart: unless-stopped

  mcp-proxy:
    build:
      context: .
      dockerfile: ./mcp-servers/Dockerfile.mcp-proxy
    ports:
      - "8090:8090"
    volumes:
      - ./keys:/app/keys:ro
    depends_on:
      - atlassian
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://sky-agent:8000/v1
      - OPENAI_API_KEY=sk-fake-key
      - WEBUI_NAME=Sky Agent
      - ENABLE_SIGNUP=true
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - sky-agent
    restart: unless-stopped

volumes:
  open-webui:

networks:
  default:
    name: sky-agent-network